### ISSUE TITLE
Resposta errada aos exercícos de CDI II

### ISSUE THREAD

**Issue by JaviMuller** [diogotcorreia/resumos-leic#310]
Há um problema na resposta ao problema 3 da ficha 12 de CDI II na resolução do Diogo Correia. 
O problema 3 pede para usar teorema de Green para calcular a area de meia elipse, o problema é que a resolução não usa teorema de Green, limita-se a enunciá-lo e calcula a área com uma parametrização da área. Para usar teorema de Green, seria preciso encontrar F nas condições em que no teorema de Green desse o integral da área de D, e.g. F(x, y) = (0, x), a seguir, parametrizar a fronteira e não o conjunto (neste caso dividiriamos na curva da elipse, parametrizando com polares alteradas (g(t) = (cos t, 2sin t)), e no segmento de recta vertical, com uma parametrização do seguinte tipo h(t) = (0, t). A seguir, calcula-se o integral na fronteira do conjunto da função F, com a formula do integral de linha num campo vectorial.

**Comment by Pesteves2002** [comment]
Ok, eu definitivamente não vou corrigir isto...

**Comment by diogotcorreia** [comment]
fine, i'll do it myself

**Comment by diogotcorreia** [comment]
It's fixed :tada:
