### ISSUE TITLE
Adicionar guia de utilização do kerberos

### ISSUE THREAD

**Issue by D-Card** [diogotcorreia/resumos-leic#383]
> 1. instalar o kerberos (no arch é krb5, no ubuntu krb5-user)
> 
> 2. obter o config do ist
> podes copiar o config do kerberos do sigma (scp sigma.tecnico.ulisboa.pt:/etc/krb5.conf .), mas da última vez tive de fazer uma pequena alteração para funcionar, portanto se n funcionar tenta usar o meu (wget https://bin.diogotc.com/raw/mabinysepi)
> copia o ficheiro para /etc/krb5.conf (e.g. sudo mv krb5.conf /etc/krb5.conf)
> 
> 3. fazer login no kerberos (kinit ist1XXXX@IST.UTL.PT)
> 
> 4. alterar o ssh config para usar o kerberos (~/.ssh/config) (adicionar o seguinte):
> Host sigma
>     HostName sigma01.tecnico.ulisboa.pt
>     User ist1XXXXX
>     GSSAPIAuthentication yes
>     GSSAPIDelegateCredentials yes
> 
> 
> 5. em vez de usar ssh ist1XXXXXX@sigma.tecnico.ulisboa.pt passar a usar sempre ssh sigma (pode-se experimentar agr para ver se funciona)
> 
> 6. alterar o remote do CVS, é mais fácil só apagar a pasta e fazer checkout again (ver site dos resumos que tem lá, mas é só substituir o ist1XXXXX@sigma.tecnico.ulisboa.pt por sigma)
> 
> also: o ticket do kerberos é apagado a cada restart, portanto precisas de fazer o passo 3 sempre que voltas a ligar o pc (ou WLS? idk) 

**self-assigned, wip**

**Comment by diogotcorreia** [comment]
Added in #384
