### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by footvaalvica** [diogotcorreia/resumos-leic#397]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 2, exercicío 3 a), espaço nulo para λ=1

### O que está incorreto e qual é a resposta certa?

A passagem da matriz para o vetor? Mesmo no fim? Não sei o suficiente para me explicar 😭

**Comment by diogotcorreia** [comment]
![image](https://user-images.githubusercontent.com/7467891/139597804-4fa4347e-e507-44be-937a-71c2421c7c96.png)

**Comment by diogotcorreia** [comment]
Fixed
