### ISSUE TITLE
[DevOps] Move to Meli (replacing Vercel)

### ISSUE THREAD

**Issue by diogotcorreia** [diogotcorreia/resumos-leic#398]
Vercel does not support GitHub Organizations on their free tier.
Since this project will most likely need to be moved to an organization in a few years, this is an obstacle that must be overcome.
Meli is an open-source and self-hosted alternative to Vercel, which implies that we need to get our own server(s) to host this project.

https://github.com/getmeli/meli

**Comment by D-Card** [comment]
I was here.

**Comment by RafDevX** [comment]
:-1: This is an education project - try to work something out with Vercel.

**Comment by D-Card** [comment]
> 👎 This is an education project - try to work something out with Vercel.

ok boomer

**Comment by diogotcorreia** [comment]
Closing this since we're going to be using a [Vercel sponsorship](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project)
