### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by DaniPalma2002** [diogotcorreia/resumos-leic#401]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 4 - 3(b)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/72202548/139835168-95a75712-790f-4f7f-bd82-9cdc6afa13e4.png)
Acredito que devia ser t³x + x em vez de t³x + 1

**Comment by diogotcorreia** [comment]
Fixed
