### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by JaviMuller** [diogotcorreia/resumos-leic#404]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 2, Exercício 3.c)

### O que está incorreto e qual é a resposta certa?

Há um erro ao escrever a forma canónica de Jordan, o que se reflete num resultado incorrecto.
A matriz `A` escreve-se na forma canónica de Jordan como sendo `A = S J S⁻¹`
Em que a matriz S é feita pelos vetores próprios que se obtêm das potências sucessivas neste caso.
Só que S não está na forma `A = [v₁ v₂ v₃]`, mas sim `A = [v₁ v₃ v₂]`, sendo que v₁ = [0 -1 1]ᵀ, v₂ = [-1, 2, -3]ᵀ, v₃ = [1, 0, 0]ᵀ
Assim, devia dar a seguinte solução:
LaTex (se quiseres fazer quick rendering, podes [aqui](https://quicklatex.com)): 
{e }^{A t }={\left[ \begin{array}{ccc}0  & -1  & 1 \\
-1  & 2  & 0 \\
1  & -3  & 0 \\
\end{array} \right] }{e }^{2 t }{\left[ \begin{array}{ccc}1  & t  & \frac{{t }^{2 }}{2 }\\
0  & 1  & t \\
0  & 0  & 1 \\
\end{array} \right] }{{\left[ \begin{array}{ccc}0  & -1  & 1 \\
-1  & 2  & 0 \\
1  & -3  & 0 \\
\end{array} \right] }}^{-1 }\Leftrightarrow {e }^{A t }=	{e }^{2 t }{\left[ \begin{array}{ccc}0  & -1  & 1 -t \\
-1  & 2 -t  & 2 t -\frac{{t }^{2 }}{2 }\\
1  & t -3  & \frac{{t }^{2 }}{2 }-3 t \\
\end{array} \right] }{\left[ \begin{array}{ccc}0  & -3  & -2 \\
0  & -1  & -1 \\
1  & -1  & -1 \\
\end{array} \right] }\Leftrightarrow {e }^{A t }={e }^{2 t }{\left[ \begin{array}{ccc}1 -t  & t  & t \\
2 t -\frac{{t }^{2 }}{2 } & \frac{{t }^{2 }}{2 }-t +1  & \frac{{t }^{2 }}{2 }-t \\
\frac{{t }^{2 }}{2 }-3 t  & -\frac{{t }^{2 }}{2 }+2 t  & -\frac{{t }^{2 }}{2 }+2 t +1 \\
\end{array} \right] }

**Comment by diogotcorreia** [comment]
Duplicate of #403

**Comment by diogotcorreia** [comment]
Fixed
