### ISSUE TITLE
[Incorrect Solution] CDI-III 2021/2022 Semana 5.1 ex 1. a)

### ISSUE THREAD

**Issue by diogotcorreia** [diogotcorreia/resumos-leic#422]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

2021/2022 Semana 5.1 ex 1. a) (resolução gaspar)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/7467891/143618217-4ad46d24-88dd-47d7-ad9e-d659ef1844af.png)

Devia ser c_2 t e^t

(o - está a mais)

**Comment by randomicecube** [comment]
Updated, thanks for bringing it up 😄
