### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by Goncalo-Palma-Nunes** [diogotcorreia/resumos-leic#433]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 5 (versão Diogo Correia) ex 3)

### O que está incorreto e qual é a resposta certa?

No último caso, está um e^(ct) = 0 => c = 0, mas e^(algo) nunca vai ser 0, portanto penso que a implicação não faz sentido. Não faço ideia qual é a resposta certa.

**Comment by diogotcorreia** [comment]
![image](https://user-images.githubusercontent.com/7467891/145306331-a47d863a-9c57-4637-b64d-d89759ffb479.png)
I've replaced with this, probably makes it more explicit what I mean (and it was incorrect anyway)

Fixed!
