### ISSUE TITLE
Mistake in solutions for 5th week CDI-III

### ISSUE THREAD

**Issue by goncalo-jp-carvalho** [diogotcorreia/resumos-leic#434]
![sc](https://user-images.githubusercontent.com/79175084/144716547-da2153ab-4afe-461a-885f-ba5546b9172d.PNG)

**Comment by Rafa10PT** [comment]
![image](https://user-images.githubusercontent.com/61294433/145303274-52de3a8d-384b-409d-ab42-3ba6307073cb.png)

**Comment by Rafa10PT** [comment]
![image](https://user-images.githubusercontent.com/61294433/145303467-e3151442-23e1-42f5-8dfc-be7cea27840f.png)

**Comment by diogotcorreia** [comment]
Fixed the 3 problems!

Next time remember to use the issue template, so it's easier to locate where the problems are.
