### ISSUE TITLE
[Incorrect Solution] CDI-III Separação de Quociente

### ISSUE THREAD

**Issue by Pesteves2002** [diogotcorreia/resumos-leic#446]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 5.2 - ex 4 a) 

### O que está incorreto e qual é a resposta certa?

Está
![image](https://user-images.githubusercontent.com/69385653/145680994-987369b5-3349-45f5-997a-2120a613620b.png)
Devia estar:
![image](https://user-images.githubusercontent.com/69385653/145681012-b1afc96b-60a7-42a9-9ab9-17f8aa3ca01d.png)

**Comment by diogotcorreia** [comment]
Fixed
