### ISSUE TITLE
[Incorrect Solution]

### ISSUE THREAD

**Issue by ValentimSts** [diogotcorreia/resumos-leic#449]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Ficha Semana 7 / exc 2.

### O que está incorreto e qual é a resposta certa?

Determinente da matriz Dg errado (**contudo, solução certa**):

![error](https://user-images.githubusercontent.com/75221226/145811221-f9e73ea9-4ffd-49c0-b6ab-dcef4e5c4503.png)

**Comment by diogotcorreia** [comment]
Fixed
