### ISSUE TITLE
[Incorrect Solution] Função ímpar descrita como par

### ISSUE THREAD

**Issue by PedroPerpetua** [diogotcorreia/resumos-leic#483]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Resolução Diogo Correia Semana 11, exercício 8

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/46409254/149510296-55e792b3-c007-4d24-8872-b2b2171dcf96.png)

|sen(x)| é uma função par, sen(nx) é uma função ímpar, logo |sen(x)| * sen(nx) é uma função ímpar e não par. Daí o resultado ser 0 (está correto, apenas a anotação que diz que a função é par está errada).

**Comment by diogotcorreia** [comment]
Fixed
