### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by BraveBoii** [diogotcorreia/resumos-leic#486]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 11; ex 3; 1a linha do calculo de an

### O que está incorreto e qual é a resposta certa?

falta um L a multiplicar pelo cosseno na separacao do integral

**Comment by diogotcorreia** [comment]
Fixed
