### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by johny4** [diogotcorreia/resumos-leic#491]
### Qual a UC que tem a resolução incorreta?

(LP) Lógica para Programação

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Exercícios de LP - Aulas Práticas, Semana 8: Prolog - Listas 2, Ex. 2

### O que está incorreto e qual é a resposta certa?

O código apresentado usa um random_between que devolve um número. Se esse número fizer parte da lista, o predicado falha logo a seguir no member, e apresenta "false" imensas vezes.

**Comment by randomicecube** [comment]
Fixed in #532, thanks for reaching out!
