### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by mario-santosgithub** [diogotcorreia/resumos-leic#501]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

CDI3 semana 11 ex 7 c)

### O que está incorreto e qual é a resposta certa?

Ao calcular an, na segunda "igualdade" quando se multiplica por 2, o limite inferior do integral deveria ser 0 (?) em vez de -1.

**Comment by diogotcorreia** [comment]
Fixed: file was updated
