### ISSUE TITLE
[Incorrect Solution] CDI3 - substituição de n errada

### ISSUE THREAD

**Issue by PedroPerpetua** [diogotcorreia/resumos-leic#514]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Ficha 14, Exercício 2b)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/46409254/151816650-93bfab47-38d4-4fec-ae12-a32056f0ef36.png)

Caso b_2 (n=2) tem no expoente n^2 = 9 em vez de n^2=4

**Comment by diogotcorreia** [comment]
Fixed: file has been updated
