### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by d-melita** [diogotcorreia/resumos-leic#531]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 5.1, exc 4 alínea c)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/81560486/152681610-e5dcbd21-e7e5-4451-b147-cbf4e8bca935.png)
no quadrado assinalado deve ser t-2 e não t+2

**Comment by diogotcorreia** [comment]
Fixed: file has been updated
