### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by randomicecube** [diogotcorreia/resumos-leic#533]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Ficha 2, Exercício 2.3 d), inverso do determinante de S

### O que está incorreto e qual é a resposta certa?

O inverso do determinante está incorretamente indicado como sendo 2i, quando na verdade deveria ser 1/2i = -i/2. Encontra-se em anexo uma _screenshot_ com o passo a partir do qual o erro mencionado aparece.

![erro-ficha-2](https://user-images.githubusercontent.com/74926943/152693747-b01709e6-0c1b-469b-8983-1cbdb185b31f.png)

**Comment by diogotcorreia** [comment]
Fixed: file has been updated
