### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by pedroclobo** [diogotcorreia/resumos-leic#535]
### Qual a UC que tem a resolução incorreta?

(Ges) Gestão

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Ficha 1, Capítulo 1, exercício 4, resposta incorreta dada como certa.

### O que está incorreto e qual é a resposta certa?

A resposta correta deveria ser a b): "Gestão de organizações é o processo de alinhar pessoas e atividades na prossecução
de objetivos comuns de forma eficiente e eficaz.".

**Comment by Pesteves2002** [comment]
Already fixed
![image](https://user-images.githubusercontent.com/69385653/152837567-578204b5-b992-4a52-9345-1854e2090d10.png)
