### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by PipesAkaTubinhos** [diogotcorreia/resumos-leic#539]
### Qual a UC que tem a resolução incorreta?

(CDI-III) Cálculo Diferencial e Integral III

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Semana 1 ex1.4: 2)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/95452003/152839674-2320f6a3-9f29-4c8a-91b4-509ee266f367.png)
na segunda linha a primitiva tem coeficiente -1 no expoente, mas depois do calculo auxilar, esse -1 é ignorado:
resultado da premitiva: tsent + cost, mas na expressao final está o mesmo, mas deveria estar o valor simetrico. 
Se estou enganado, avisa plz :D

**Comment by diogotcorreia** [comment]
Fixed: file has been updated
