### ISSUE TITLE
[Incorrect Solution] 

### ISSUE THREAD

**Issue by go-ncalo** [diogotcorreia/resumos-leic#631]
### Qual a UC que tem a resolução incorreta?

(TC) Teoria da Computação

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Capítulo 3, 2.1 alínea i)

### O que está incorreto e qual é a resposta certa?

![image](https://user-images.githubusercontent.com/75749966/160244529-5f9d6024-9968-40c2-b709-93b468789265.png)
Ter esta parte neste exercício não faz sentido, porque aceita a palavra 000, por exemplo... Acredito que tenhas copiado a alínea de cima e esqueceste-te de apagar aquela parte

**Comment by diogotcorreia** [comment]
Fixed, thanks
