### ISSUE TITLE
[Incorrect Solution]

### ISSUE THREAD

**Issue by creaaidev** [diogotcorreia/resumos-leic#636]
### Qual a UC que tem a resolução incorreta?

(TC) Teoria da Computação

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Capítulo 2, 2

### O que está incorreto e qual é a resposta certa?

As últimas transições []->1,R e []->0,R estão trocadas (e.g. 011 fica 010, o que não devia acontecer).
![image](https://user-images.githubusercontent.com/35880776/160291808-5435c647-ada8-4db3-9a7b-32e34f59f512.png)

**Comment by diogotcorreia** [comment]
Fixed, thanks
