### ISSUE TITLE
Falta um x->next = NULL na função insertEnd

### ISSUE THREAD

**Issue by pearsettings44** [diogotcorreia/resumos-leic#687]
### Qual a UC que tem a resolução incorreta?

(IAED) Introdução a Algoritmos e Estruturas de Dados

### Em que ficha/capítulo/exercício/passo se encontra o erro?

Estruturas de Dados (Cheat Sheet) - Lista Simplesmente Ligada - Função insertEnd

### O que está incorreto e qual é a resposta certa?

Após "x->value = number;" e "aux->value = number;" deveria estar "x->next = NULL".

**Comment by randomicecube** [comment]
Fixed in #688
